
name: Update Gist

on:
  push:
    branches: master

  schedule:
    - cron: "0 */3 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./dist/index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 84e1d6266482b6fa0a2377653d8a1f28
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
